vich_uploader:
    db_driver: orm

    mappings:
        vignette_category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
